
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'CALL DO ELSE EQEQ EQUALS GREATER GREATEREQ ID IF JUMP LBRACE LESS LESSEQ LPAREN NEWLINE NOTEQ NUMBER RBRACE RESPONSE RPAREN SEMICOLON SET SPEAK STRING VARIABLEscript : do_module\n              | script do_moduledo_module : DO ID LBRACE c RBRACEc : statement\n         | c statementstatement : SET ID EQUALS expr SEMICOLONstatement : SPEAK STRING SEMICOLONstatement : JUMP ID SEMICOLONstatement : IF LPAREN condition RPAREN LBRACE c RBRACEstatement : IF LPAREN condition RPAREN LBRACE c RBRACE ELSE LBRACE c RBRACEcondition : expr EQEQ expr\n                 | expr NOTEQ expr\n                 | expr GREATER expr\n                 | expr LESS expr\n                 | expr GREATEREQ expr\n                 | expr LESSEQ exprstatement : CALL ID SEMICOLONcondition : exprexpr : IDexpr : CALL IDexpr : STRING\n            | VARIABLE\n            | NUMBER'
    
_lr_action_items = {'DO':([0,1,2,4,14,],[3,3,-1,-2,-3,]),'$end':([1,2,4,14,],[0,-1,-2,-3,]),'ID':([3,9,11,13,19,21,27,34,35,36,37,38,39,],[5,16,18,20,26,26,40,26,26,26,26,26,26,]),'LBRACE':([5,33,51,],[6,42,52,]),'SET':([6,7,8,15,22,23,31,41,42,49,50,52,53,54,],[9,9,-4,-5,-7,-8,-17,-6,9,9,-9,9,9,-10,]),'SPEAK':([6,7,8,15,22,23,31,41,42,49,50,52,53,54,],[10,10,-4,-5,-7,-8,-17,-6,10,10,-9,10,10,-10,]),'JUMP':([6,7,8,15,22,23,31,41,42,49,50,52,53,54,],[11,11,-4,-5,-7,-8,-17,-6,11,11,-9,11,11,-10,]),'IF':([6,7,8,15,22,23,31,41,42,49,50,52,53,54,],[12,12,-4,-5,-7,-8,-17,-6,12,12,-9,12,12,-10,]),'CALL':([6,7,8,15,19,21,22,23,31,34,35,36,37,38,39,41,42,49,50,52,53,54,],[13,13,-4,-5,27,27,-7,-8,-17,27,27,27,27,27,27,-6,13,13,-9,13,13,-10,]),'RBRACE':([7,8,15,22,23,31,41,49,50,53,54,],[14,-4,-5,-7,-8,-17,-6,50,-9,54,-10,]),'STRING':([10,19,21,34,35,36,37,38,39,],[17,28,28,28,28,28,28,28,28,]),'LPAREN':([12,],[19,]),'EQUALS':([16,],[21,]),'SEMICOLON':([17,18,20,26,28,29,30,32,40,],[22,23,31,-19,-21,-22,-23,41,-20,]),'VARIABLE':([19,21,34,35,36,37,38,39,],[29,29,29,29,29,29,29,29,]),'NUMBER':([19,21,34,35,36,37,38,39,],[30,30,30,30,30,30,30,30,]),'RPAREN':([24,25,26,28,29,30,40,43,44,45,46,47,48,],[33,-18,-19,-21,-22,-23,-20,-11,-12,-13,-14,-15,-16,]),'EQEQ':([25,26,28,29,30,40,],[34,-19,-21,-22,-23,-20,]),'NOTEQ':([25,26,28,29,30,40,],[35,-19,-21,-22,-23,-20,]),'GREATER':([25,26,28,29,30,40,],[36,-19,-21,-22,-23,-20,]),'LESS':([25,26,28,29,30,40,],[37,-19,-21,-22,-23,-20,]),'GREATEREQ':([25,26,28,29,30,40,],[38,-19,-21,-22,-23,-20,]),'LESSEQ':([25,26,28,29,30,40,],[39,-19,-21,-22,-23,-20,]),'ELSE':([50,],[51,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'script':([0,],[1,]),'do_module':([0,1,],[2,4,]),'c':([6,42,52,],[7,49,53,]),'statement':([6,7,42,49,52,53,],[8,15,8,15,8,15,]),'condition':([19,],[24,]),'expr':([19,21,34,35,36,37,38,39,],[25,32,43,44,45,46,47,48,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> script","S'",1,None,None,None),
  ('script -> do_module','script',1,'p_script','yacc.py',6),
  ('script -> script do_module','script',2,'p_script','yacc.py',7),
  ('do_module -> DO ID LBRACE c RBRACE','do_module',5,'p_do_module','yacc.py',14),
  ('c -> statement','c',1,'p_c','yacc.py',23),
  ('c -> c statement','c',2,'p_c','yacc.py',24),
  ('statement -> SET ID EQUALS expr SEMICOLON','statement',5,'p_statement_set','yacc.py',31),
  ('statement -> SPEAK STRING SEMICOLON','statement',3,'p_statement_speak','yacc.py',40),
  ('statement -> JUMP ID SEMICOLON','statement',3,'p_statement_jump','yacc.py',47),
  ('statement -> IF LPAREN condition RPAREN LBRACE c RBRACE','statement',7,'p_statement_if','yacc.py',54),
  ('statement -> IF LPAREN condition RPAREN LBRACE c RBRACE ELSE LBRACE c RBRACE','statement',11,'p_statement_if_else','yacc.py',63),
  ('condition -> expr EQEQ expr','condition',3,'p_condition_compare','yacc.py',72),
  ('condition -> expr NOTEQ expr','condition',3,'p_condition_compare','yacc.py',73),
  ('condition -> expr GREATER expr','condition',3,'p_condition_compare','yacc.py',74),
  ('condition -> expr LESS expr','condition',3,'p_condition_compare','yacc.py',75),
  ('condition -> expr GREATEREQ expr','condition',3,'p_condition_compare','yacc.py',76),
  ('condition -> expr LESSEQ expr','condition',3,'p_condition_compare','yacc.py',77),
  ('statement -> CALL ID SEMICOLON','statement',3,'p_statement_call','yacc.py',81),
  ('condition -> expr','condition',1,'p_condition_expr','yacc.py',90),
  ('expr -> ID','expr',1,'p_expr_id','yacc.py',94),
  ('expr -> CALL ID','expr',2,'p_expr_call','yacc.py',98),
  ('expr -> STRING','expr',1,'p_expr_literal','yacc.py',105),
  ('expr -> VARIABLE','expr',1,'p_expr_literal','yacc.py',106),
  ('expr -> NUMBER','expr',1,'p_expr_literal','yacc.py',107),
]
